### ISSUE TITLE
Could you provide a checkpoint

### ISSUE THREAD

**Issue by jianyulei1** [alibaba-mmai-research/Masked-Action-Recognition#1]
CHECKPOINT_FILE_PATH: "checkpoints/video-mae-k400-1600ep-transferrd.pth" 
Excuse me where to download this checkpoint.

**Comment by qinzhi-0110** [comment]
Thanks for your attention. I have supplemented this instruction in Readme: Getting Pre-trained Checkpoints section.

**Comment by jianyulei1** [comment]
Thank you very much.
