### ISSUE TITLE
module 'models.utils.losses' has no attribute 'Loss_MaeCls'

### ISSUE THREAD

**Issue by jianyulei1** [alibaba-mmai-research/Masked-Action-Recognition#2]
I encountered the following error：
File "/data2/liwj/Masked-Action-Recognition-main/tools/train_net.py", line 142, in train_epoch
    loss_model, loss_in_parts_model = losses.Loss_MaeCls(cfg, agent_output, model_output, None, labels, cur_epoch + cfg.TRAIN.NUM_FOLDS * float(cur_iter) / data_size)
AttributeError: module 'models.utils.losses' has no attribute 'Loss_MaeCls'
I hope the author can answer me, thank you very much.

**Comment by qinzhi-0110** [comment]
I am sorry for my oversight, I have fixed this bug now. You can update your code to solve this.

**Comment by jianyulei1** [comment]
Thank you！！！
