### ISSUE TITLE
AttributeError: module utils/checkpoint.py' has no attribute 'save_checkpoint_dqn'

### ISSUE THREAD

**Issue by jianyulei1** [alibaba-mmai-research/Masked-Action-Recognition#3]
AttributeError: module utils/checkpoint.py' has no attribute 'save_checkpoint_dqn'
line 420, in train_net.py
There are some mistakes, is 'save_checkpoint_dqn' changed to 'save_checkpoint' ?

**Comment by qinzhi-0110** [comment]
You can replace save_checkpoint_dqn to save_checkpoint, and remove  the parameter: "agent".
I have updated this in train_net.py.
